#ifndef TORT_ENTITY_TYPES_H
#define TORT_ENTITY_TYPES_H

#define ENTITY_TYPE_USER 0
#define ENTITY_TYPE_TRANSITION 1
#define ENTITY_TYPE_NOODLETOWN_MAP 2
#define ENTITY_TYPE_MY_HOUSE_MAP 3
#define ENTITY_TYPE_SIGN_INTERACTION 4
#define ENTITY_TYPE_SIGN_DIALOG 5
#define ENTITY_TYPE_SMALL_BLOCK 6
#define ENTITY_TYPE_TILE_BLOCK 7
#define ENTITY_TYPE_NARROW_BLOCK 8
#define ENTITY_TYPE_HORIZONTAL_BLOCK 9
#define ENTITY_TYPE_VERTICAL_BLOCK 10
#define ENTITY_TYPE_TRANSITION_BLOCK 11
#define ENTITY_TYPE_HOUSE_TRANSITION 12

// total number of entity types
#define ENTITY_TYPE_MAX 13

#endif